server:
  port: 8080

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3307/userdb?useSSL=false&serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:XzQ7Bz5LJ9i6t8mN7yNp9tA+38oZTt7Zb7VcF5w4zQqE4Z1eHhXb+J7rSc+vQ8Qp}
  expirationMs: ${JWT_EXPIRATION_MS:3600000}
